### ISSUE TITLE
Custom Proxy .strip() error when CUSTOM_PROXY is commented

### ISSUE THREAD

**Issue by zaheeruddinbabur** [volkan/appointment-finder-berlin#1]
Hi,

Thanks for this great script. I am not using any proxy and when I comment the proxy env variable out, I get the following error:

scraper_appointment_finder_1  | 
scraper_appointment_finder_1  | 2021-09-07 12:56:19 [twisted] CRITICAL: 
scraper_appointment_finder_1  | Traceback (most recent call last):
scraper_appointment_finder_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
scraper_appointment_finder_1  |     result = current_context.run(gen.send, result)
scraper_appointment_finder_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 63, in run
scraper_appointment_finder_1  |     return f(*args, **kwargs)
scraper_appointment_finder_1  |   File "/usr/local/lib/python3.6/site-packages/scrapy/crawler.py", line 87, in crawl
scraper_appointment_finder_1  |     self.engine = self._create_engine()
scraper_appointment_finder_1  |   File "/usr/local/lib/python3.6/site-packages/scrapy/crawler.py", line 101, in _create_engine
scraper_appointment_finder_1  |     return ExecutionEngine(self, lambda _: self.stop())
scraper_appointment_finder_1  |   File "/usr/local/lib/python3.6/site-packages/scrapy/core/engine.py", line 69, in __init__
scraper_appointment_finder_1  |     self.downloader = downloader_cls(crawler)
scraper_appointment_finder_1  |   File "/usr/local/lib/python3.6/site-packages/scrapy/core/downloader/__init__.py", line 83, in __init__
scraper_appointment_finder_1  |     self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
scraper_appointment_finder_1  |   File "/usr/local/lib/python3.6/site-packages/scrapy/middleware.py", line 53, in from_crawler
scraper_appointment_finder_1  |     return cls.from_settings(crawler.settings, crawler)
scraper_appointment_finder_1  |   File "/usr/local/lib/python3.6/site-packages/scrapy/middleware.py", line 35, in from_settings
scraper_appointment_finder_1  |     mw = create_instance(mwcls, settings, crawler)
scraper_appointment_finder_1  |   File "/usr/local/lib/python3.6/site-packages/scrapy/utils/misc.py", line 166, in create_instance
scraper_appointment_finder_1  |     instance = objcls.from_crawler(crawler, *args, **kwargs)
scraper_appointment_finder_1  |   File "/usr/local/lib/python3.6/site-packages/scrapy_proxies/randomproxy.py", line 78, in from_crawler
scraper_appointment_finder_1  |     return cls(crawler.settings)
scraper_appointment_finder_1  |   File "/usr/local/lib/python3.6/site-packages/scrapy_proxies/randomproxy.py", line 64, in __init__
scraper_appointment_finder_1  |     parts = re.match('(\w+://)([^:]+?:[^@]+?@)?(.+)', custom_proxy.strip())
scraper_appointment_finder_1  | AttributeError: 'NoneType' object has no attribute 'strip'
appointment-finder-berlin_scraper_appointment_finder_1 exited with code 1

**Comment by volkan** [comment]
Hey @zaheeruddinbabur ,

Thank you for the feedback. Please pull the latest version of the code. 
Just comment with line comment the `CUSTOM_PROXY`

Thanks

**Comment by volkan** [comment]
I am closing the issue. If the issue continues, feel free to re-open it.
