### ISSUE TITLE
Is this only to be used for the four services mentioned in the README?

### ISSUE THREAD

**Issue by saveshodhan** [volkan/appointment-finder-berlin#4]
hi,

can this software be used only for the four services mentioned in the README? i would like to make an appointment for residence permit ([here](https://service.berlin.de/dienstleistung/324661/)), but currently there are no appointments, so im not sure what the URL should be..

thanks!

**Comment by volkan** [comment]
Hi,

Unfortunately not. I'm looking for another solution for https://otv.verwalt-berlin.de/ams/TerminBuchen but I haven't been able to see the appointment page yet.

**Comment by saveshodhan** [comment]
hi,

no worries, thanks for the update. i will close this for now. thanks!
